parameters:

    filesBundle.path.entity: Parsingcorner\FilesBundle\Entity\Path
    filesBundle.filePath.entity: Parsingcorner\FilesBundle\Entity\FilePath
    filesBundle.handler.class: Parsingcorner\FilesBundle\Model\FilesHandler
    filesBundle.entitiesBuilder.class: Parsingcorner\FilesBundle\Model\FilesEntitiesBuilder
    filesBundle.fileMaster.class: Parsingcorner\FilesBundle\Model\FileMaster
    filesBundle.filesContentProcessing.class: Parsingcorner\FilesBundle\Model\FilesContentProcessing

    filesBundle.pathMaster.class: Parsingcorner\FilesBundle\Model\PathMaster
    filesBundle.pathHandler.class: Parsingcorner\FilesBundle\Model\PathHandler

    filesBundle.defaultDirPermissions: 0755

services:
    filesBundle.handler:
        class: %filesBundle.handler.class%
        arguments:
          - @filesBundle.fileMaster
          - @filesBundle.entitiesBuilder

    filesBundle.fileMaster:
        class: %filesBundle.fileMaster.class%

    filesBundle.pathHandler:
        class: %filesBundle.pathHandler.class%
        arguments:
            - @filesBundle.pathMaster

    filesBundle.pathMaster:
        class: %filesBundle.pathMaster.class%
        arguments:
            - %filesBundle.defaultDirPermissions%

    filesBundle.entitiesBuilder:
        class: %filesBundle.entitiesBuilder.class%

    filesBundle.filesContentProcessing:
        class: %filesBundle.filesContentProcessing.class%
        arguments:
            - @filesBundle.fileMaster
